### ISSUE TITLE
Unable to start the server in multiplayer mode

### ISSUE THREAD

**Issue by Kaneikiun101** [kiber-pacan/item-placer#3]
[logs.zip](https://github.com/user-attachments/files/16323565/logs.zip)
This is my report.

**Comment by kiber-pacan** [comment]
gonna start fixing mod as soon as i arrive home

**Comment by Kaneikiun101** [comment]
> 我一到家就开始修mod

Has it been fixed?

**Comment by kiber-pacan** [comment]
No

**Comment by kiber-pacan** [comment]
Still not home

**Comment by kiber-pacan** [comment]
fixed
