### ISSUE TITLE
The mod crashed my game.

### ISSUE THREAD

**Issue by Kaneikiun101** [kiber-pacan/item-placer#6]
This mod was crashing my game, as soon as I touched Armor Stand my game would crash, I removed the mod and everything worked fine!
[crash-reports.zip](https://github.com/user-attachments/files/16568268/crash-reports.zip)

**Comment by Kaneikiun101** [comment]
This is just one of the crashes, maybe there are more, I only know of this one trigger so far

**Comment by kiber-pacan** [comment]
FIXED
