### ISSUE TITLE
Latest update broke the mod for me

### ISSUE THREAD

**Issue by MangoLassie142** [kiber-pacan/item-placer#7]
The latest update (1.8.3) totally broke the mod for me. I can no longer rotate any items placed on the floor but it still makes the sound, i can no longer pick items up with right click, but it makes a sound, and it changed the orientation that some items were placed which broke some decorations.

**Comment by kiber-pacan** [comment]
minecraft version?

**Comment by MangoLassie142** [comment]
Fabric 1.20.1 :)

**Comment by kiber-pacan** [comment]
try breaking laying item blocks

**Comment by kiber-pacan** [comment]
and placing them again

**Comment by kiber-pacan** [comment]
it happened because i rewrote my stupid braindead code

**Comment by kiber-pacan** [comment]
inactive
